### PR TITLE
Get /app/project/{project_id}/access

### PR DESCRIPTION
**Pull request by luxusko**
Resolves #138

### CODE REVIEW

**Comment by MarcelGeo** [comment]
@luxusko I don't see tests for new endpoint.

**Review by MarcelGeo — CHANGES_REQUESTED** [review]

**Review by harminius — COMMENTED** [review]
I agree with MarceGeo.

**Comment by MarcelGeo** [comment]
Logic: @luxusko , agreed with @varmar05 

    in case of GLOBAL_WRITE - everybody with reader 🔽 in project.access will be writer 🔼 , everybody with owner in project.access will be owner (NOT WRITER)

**Review by MarcelGeo — APPROVED** [review]
Looks ok now :)

**Pull request merged**
